swagger: '2.0'
info:
  version: 1.1.4
  title: Japanese Health Monitor API documentation
  description: '@Author, Narandhran Thangavel'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Orgware
    email: admin@orgware.com
    url: 'https://www.orgware.in/'
host: localhost:8084
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header